name: Build wheels

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm
          ref: v0.8.5.post1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD_MACOS: cp312-*
          CIBW_BUILD_WINDOWS: cp312-*
          CIBW_BUILD_LINUX: cp312-*
          CIBW_BEFORE_BUILD_LINUX: yum install -y numactl-devel
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.12,<3.13"
          CIBW_BUILD_FRONTEND: "build[uv]"
          CIBW_ARCHS: native
          CIBW_SKIP: "*musllinux*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX:
            "auditwheel repair -w /tmp/cibuildwheel/repaired_wheel {wheel}
            --exclude libcuda.so --exclude libcuda.so.1 --exclude libc10.so
            --exclude libc10_cuda.so --exclude libtorch.so --exclude
            libtorch_python.so --exclude libtorch_cpu.so --exclude
            libtorch_cuda.so --exclude libtorch_cuda_cpp.so --exclude
            libtorch_cuda_cu.so --exclude libcudart.so.11 --exclude
            libcudart.so.12 --exclude libcudart.so.11.0 --exclude
            libcudart.so.12.0 --exclude libcurand.so.10 --exclude
            libcufile_rdma.so --exclude libcufile_rdma.so.1 --exclude
            libcufile.so.1 --exclude libcufile.so.0 --exclude libcufile.so"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS:
            "delocate-wheel --ignore-missing-dependencies -w {dest_dir} -v
            {wheel}"
          CIBW_ENVIRONMENT_LINUX: VLLM_TARGET_DEVICE=cpu
            UV_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cpu
            UV_INDEX_STRATEGY=unsafe-best-match
          CIBW_ENVIRONMENT_MACOS: VLLM_TARGET_DEVICE=cpu

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
