name: Format

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"

      - run: npx prettier@3.6.2 --check "**/*.{json5,jsonc,json,yaml,yml,mjs,js,jsx,ts,tsx}"
      - run: npx prettier@3.6.2 --check --prose-wrap always "**/*.{mdx,md}"
